### ISSUE TITLE
Task vs. Threads

### ISSUE THREAD

**Issue by lutz** [mirinsoft/burnbytes#5]
You use often threads but in new applications (in my opinion)  the `Task`class is the modern way, So in this case we should use modern features of .net.

**Comment by Belim** [comment]
I took a quick pass on the original code (it's built from https://github.com/thebookisclosed/Comet) and polished the GUI so far. I thought it was a pity that it was no longer maintained and wanted to save it. There is indeed still a lot to do and I am happy to see someone take up on it because I am currently focusing on other projects and still at my beginnings with C#

If you have it in german and globalize it, I will push the release immediately. Thanks for the help :pray:
